"""Generation of artifacts/ingest_report.md.

Appends rather than overwrites, so P1 status and the later P3 embedding
statistics live in one document.
"""

from __future__ import annotations

import re
from typing import Any

import config

SECTION = "## Sources"


def _escape(value: Any) -> str:
    return str(value if value is not None else "").replace("|", "\\|")


def _flag_icon(flag: str) -> str:
    return {
        "ok": "ok",
        "fetch_failed": "FETCH FAILED",
        "suspected_client_rendered": "SUSPECTED CLIENT-RENDERED",
        "extract_failed": "EXTRACT FAILED",
    }.get(flag, flag)


def _compose(rows: list[dict[str, Any]], stats: str | None) -> str:
    counts: dict[str, int] = {}
    for row in rows:
        counts[row.get("flag", "ok")] = counts.get(row.get("flag", "ok"), 0) + 1

    lines = [
        SECTION,
        "",
        f"- rows: {len(rows)}",
        "- flags: "
        + ", ".join(f"{flag}={count}" for flag, count in sorted(counts.items())),
        f"- min_extracted_chars threshold: {config.MIN_EXTRACTED_CHARS}",
        "",
        "| source_id | scheme | plan | doc_type | flag | http | bytes | blocks | tables | extracted_chars | detail |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]

    for row in rows:
        lines.append(
            "| {sid} | {scheme} | {plan} | {doc_type} | {flag} | {http} | {size} | {blocks} | "
            "{tables} | {chars} | {detail} |".format(
                sid=_escape(row.get("source_id")),
                scheme=_escape(row.get("scheme")),
                plan=_escape(row.get("plan")),
                doc_type=_escape(row.get("doc_type")),
                flag=_flag_icon(str(row.get("flag", "ok"))),
                http=_escape(row.get("http_status", "")),
                size=_escape(row.get("byte_size", "")),
                blocks=_escape(row.get("block_count", "")),
                tables=_escape(row.get("table_count", "")),
                chars=_escape(row.get("extracted_chars", "")),
                detail=_escape(row.get("error") or ""),
            )
        )

    problem = [r for r in rows if r.get("flag") != "ok"]
    lines.append("")
    if problem:
        lines.append("### Needs attention before P2")
        lines.append("")
        for row in problem:
            lines.append(
                f"- **{row.get('source_id')}** `{row.get('flag')}` "
                f"{row.get('error') or ''} {row.get('url', '')}".rstrip()
            )
    else:
        lines.append("### Needs attention before P2")
        lines.append("")
        lines.append("None. All enabled sources extracted cleanly.")

    if stats:
        lines.extend(["", "## Embedding", "", stats])

    return "\n".join(lines) + "\n"


def write_report(rows: list[dict[str, Any]]) -> str:
    """Replace the sources section of the report, preserving any other sections."""
    config.ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
    destination = config.INGEST_REPORT
    body = _compose(rows, None)

    existing = destination.read_text(encoding="utf-8") if destination.exists() else ""
    tail = ""
    if SECTION in existing:
        remainder = existing.split(SECTION, 1)[1]
        tail = remainder.split("\n## ", 1)[1] if "\n## " in remainder else ""
        tail = f"\n## {tail}" if tail.strip() else ""

    if existing.startswith("# "):
        header = existing.split("\n", 1)[0]
        destination.write_text(f"{header}\n\n{body}{tail}", encoding="utf-8")
    else:
        destination.write_text(
            f"# Ingest Report\n\n_Generated by src/extract.py_\n\n{body}{tail}", encoding="utf-8"
        )

    return str(destination)


def append_embedding_stats(stats: str) -> None:
    """Add the embedding section without disturbing the sources table."""
    destination = config.INGEST_REPORT
    existing = destination.read_text(encoding="utf-8") if destination.exists() else ""
    cleaned = re.sub(r"\n## Embedding\n.*?(?=\n## |\Z)", "", existing, flags=re.S)
    destination.write_text(cleaned.rstrip() + f"\n\n## Embedding\n\n{stats}\n", encoding="utf-8")